version: '3.8'

services:
  app:
    build:
      context: ./docker/php/
      dockerfile: Dockerfile.dev
      args:
        WWWUSER: 1000
        WWWGROUP: 1000
    image: laravel-app
    container_name: laravel-app
    volumes:
      - ./:/var/www/html
    ports:
      - "9000:9000"   # PHP-FPM port
    networks:
      - laravel-network
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel-network
    depends_on:
      - app

  db:
    image: postgres:17
    container_name: laravel-postgres
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: sail
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge

volumes:
  pgdata:
