version: '3.8'

services:
  app:
    build:
      context: ./php
    container_name: expense-app
    working_dir: /var/www/html
    volumes:
      - ../app:/var/www/html
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - expense-network
    depends_on:
      - db

  webserver:
    image: nginx:alpine
    container_name: expense-nginx
    ports:
      - "8080:80"
    volumes:
      - ../app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - expense-network
    depends_on:
      - app

  db:
    image: postgres:15
    container_name: expense-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: expense_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - expense-network

networks:
  expense-network:

volumes:
  pgdata:
